Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2023-07, with the labels that each got.

#658 New clay electrolysis recipe
  src/main/java/com/dreammaster/gthandler/recipes/ElectrolyzerRecipes.java
Labels: affects balance

#656 Remove non-existent ores from DD voidminer
  src/main/java/com/dreammaster/bartworksHandler/VoidMinerLoader.java
Labels: affects balance, merge when ready

#662 Time <-> Space conversion recipes
  src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
Labels: affects balance

#664 Add compressor recipe for nether star block from dust
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
Labels: affects balance

#666 Fluid digital singularity recipe + Fluid Quantum Drive recipe
  src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Labels: affects balance

#669 Remove broken recipes from extra trees
  src/main/java/com/dreammaster/scripts/ScriptExtraTrees.java
Labels: merge when ready

#671 Recipes for new quad input hatches
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: affects balance

#674 Fix Oxygen Tank recipe and make the infinite oxy tank recipe more flexible
  src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
Labels: affects balance

#680 More new assembler recipes
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: Affects Balance

#683 Adding Better Optical Fiber Cable Recipe
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: Affects Balance

#685 Fix 10 recipes
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
Labels: Affects Balance

#687 More optical CPU recipes
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Labels: Affects Balance

#686 Add recipes for crafting input hatches
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Labels: Affects Balance
