Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2024-11, with the labels that each got.

#1063 Remove callisto ice ic2 coolant cutting recipe
  src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
Labels: bug fix

#1067 Remove Ancient Blocks from Chisel
  src/main/java/com/dreammaster/scripts/ScriptChisel.java
Labels: ongoing freeze - do not merge

#1070 Changed Ichorcloth Recipe to remove screws and screwdriver
  src/main/java/com/dreammaster/scripts/ScriptThaumicTinkerer.java
Labels: enhancement

#1073 fix small bop to gt color bug
  src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
Labels: bug fix

#1059 Added Infinity Water Cell Recipe
  src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
Labels: Affects Balance, new feature

#1078 Add lepidopterology chest to Script
  src/main/java/com/dreammaster/scripts/ScriptForestry.java
Labels: bug fix

#1086 9x Oreberry maceration to remove tiny dust
  src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
Labels: enhancement

#1048 Recipe for Portable Shower
  src/main/java/com/dreammaster/scripts/ScriptWarpTheory.java
Labels: Affects Balance, ongoing freeze - do not merge

#1092 Fixed amount in Good Circuit Recipe
  src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
Labels: bug fix

#1095 Fix circuit oredict, nbt sensitivity on universe cells
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Labels: bug fix
