Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2024-10, with the labels that each got.

#1016 Fix EIC recipe using itnt
  src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
Labels: bug fix

#1017 Fixes the stoik aluminium hydroxide and sodium dupe of sodium aluminate
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
Labels: bug fix

#1018 Remove collisions
  src/main/java/com/dreammaster/bartworksHandler/BioItemLoader.java
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
Labels: bug fix

#1022 fix ichorium block infusion recipe
  src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java
Labels: bug fix

#1025 Add assembler recipes for some new items used in stargate
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
  src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
Labels: enhancement

#1026 Hide render blocks from NEI
  src/main/java/com/dreammaster/auxiliary/NEIGTNewHorizonsConfig.java
Labels: enhancement

#1027 Rework endgame nether star processing
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ImplosionCompressorRecipes.java
Labels: enhancement

#1037 readd iron ore gravel recipe
  src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
Labels: bug fix

#1038 Change small/tiny ash to chanced output full dust in EBF
  src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
Labels: enhancement

#1036 Add recipes for Item Holder Covers
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: bug fix

#1035 Add a recipe to the Architect's Glowbrush
  src/main/java/com/dreammaster/scripts/ScriptArchitectureCraft.java
Labels: ongoing freeze - do not merge, new feature

#1039 Fix good circuit recipe
  src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
Labels: enhancement

#1033 Move Digital Singularities from Dire table to Space Asssembler
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
  src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
  src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
Labels: Affects Balance

#1040 Remove recipes for high tier singleblock pumps
  src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
  src/main/java/com/dreammaster/gthandler/enums/MetaTileEntityIDs.java
  src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
  src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java
Labels: bug fix

#1019 switch 64k to sensor and emitter for advanced infuson provider
  src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
Labels: Affects Balance

#1023 Add ichorium block compressor recipe
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
Labels: Affects Balance

#1045 Fix AL recipes for dyson parts, stargate, etc.
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Labels: bug fix

#1044 Downtier wireless data hatches to UEV
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Labels: Affects Balance

#1053 Fix LuV world accelerator assembler recipe
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: bug fix
