Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2024-12, with the labels that each got.

#1098 fix a few recipe conflicts
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: bug fix

#1103 Fix custom drops chances
  src/main/java/com/dreammaster/modcustomdrops/CustomDropsHandler.java
Labels: bug fix

#1106 Fix avaritia tool recipes in NEI
  src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
Labels: bug fix

#1105 Added recipes in oreder to get currently unobtainable foods
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
  src/main/java/com/dreammaster/scripts/ScriptExtraTrees.java
  src/main/java/com/dreammaster/scripts/ScriptThaumicExploration.java
  src/main/java/com/dreammaster/scripts/ScriptThaumicHorizons.java
Labels: new feature

#1099 migrate air filter to use new style turbine rendering
  src/main/java/com/dreammaster/gthandler/casings/GT_Block_CasingsNH.java
  src/main/java/com/dreammaster/gthandler/multiAirFilter/GT_MetaTileEntity_AirFilterBase.java
Labels: enhancement

#1085 Wire rebalance part 2, electric bugaloo or whatever
  src/main/java/com/dreammaster/gthandler/GT_Loader_Wires.java
Labels: Affects Balance

#1090 Add ME output hatches+singularity cell recipe
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Labels: enhancement

#1091 Added assembler recipes for all missing transformers
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: enhancement

#1111 priest trade improvements
  src/main/java/com/dreammaster/NHTradeHandler/NHTradeHandler.java
  src/main/java/com/dreammaster/main/MainRegistry.java
Labels: enhancement

#1113 Nerf glass loop
  src/main/java/com/dreammaster/gthandler/recipes/FluidExtractorRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
Labels: Affects Balance

#1118 Fix artificial universe cell recipes
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Labels: bug fix

#1119 Don't allow railcraft crowbars in crafting
  src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java
Labels: bug fix

#1122 fix electric scanner recipes
  src/main/java/com/dreammaster/detrav/ScannerTools.java
Labels: bug fix

#1123 fix all the rocket controller recipes
  src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Labels: bug fix

#1124 Project red tinker fix
  src/main/java/com/dreammaster/scripts/ScriptProjectRed.java
Labels: bug fix

#1126 remove vanilla stone tools
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
Labels: Affects Balance

#1125 Color upgrade recipe change
  src/main/java/com/dreammaster/scripts/ScriptNuclearControl.java
Labels: bug fix

#1127 Fix UEV+ casing and hull recycling recipes
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/GT_Loader_Machines.java
Labels: bug fix

#1121 First round of EFR recipe integration
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
  src/main/java/com/dreammaster/scripts/ScriptLoader.java
Labels: :construction: Testing on Zeta

#1132 Hatch/bus type change shaped to shapeless
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Labels: enhancement
