Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2024-09, with the labels that each got.

#967 Rework indium comb processing
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/recipes/CentrifugeRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/VacuumFurnaceRecipes.java
Labels: Affects Balance

#969 Increase speed of second dtpf quantum anomaly recipe
  src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
Labels: Affects Balance

#974 Final recipes for compressors 2-4
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/PolarizerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
Labels: Affects Balance

#986 Fix swapped recipe times/voltages
  src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAvaritiaAddons.java
Labels: bug

#989 Don't randomly make infcat cost 8x as much
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Labels: bug

#991 Fix mixer recipe
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
Labels: bug fix

#996 fix random pack breakage of the day no2
  src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
Labels: bug fix

#997 Reduce neutronium casing cost
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
Labels: Affects Balance

#980 2.7 Stargate
  src/main/java/com/dreammaster/auxiliary/NEIGTNewHorizonsConfig.java
  src/main/java/com/dreammaster/gthandler/CustomItemList.java
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/GT_Loader_Items.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AutoclaveRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ExtractorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
  src/main/java/com/dreammaster/item/ItemList.java
  src/main/java/com/dreammaster/scripts/ScriptSGCraft.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
  src/main/resources/assets/dreamcraft/textures/items/itemHarmonicChevron.png
  src/main/resources/assets/dreamcraft/textures/items/itemHarmonicChevron.png.mcmeta
  src/main/resources/assets/dreamcraft/textures/items/itemHarmonicFramePart.png
  src/main/resources/assets/dreamcraft/textures/items/itemHarmonicFramePart.png.mcmeta
  src/main/resources/assets/dreamcraft/textures/items/itemHarmonicGatePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemHarmonicGatePlate.png.mcmeta
  src/main/resources/assets/dreamcraft/textures/items/itemStargateCrystalAncients.png
  src/main/resources/assets/dreamcraft/textures/items/itemStargateCrystalDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemStargateDustAncients.png
Labels: Affects Balance

#988 Fix eoh preadding planet block recipes void stored astral arrays
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
Labels: enhancement

#998 Add Antimatter recipes
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/LaserEngraverRecipes.java
Labels: enhancement, Affects Balance, merge when ready

#999 Fix inconsistent nether flesh recipes
  src/main/java/com/dreammaster/scripts/ScriptHarvestcraftNether.java
Labels: bug fix

#1000 Collisions etc
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ImplosionCompressorRecipes.java
Labels: bug fix

#1002 Remove railcraft oredict
  src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java
Labels: bug fix

#1003 Change alternate eternal singularity recipe
  src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Labels: bug fix

#1005 fix several open blocks assembler recipes
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: bug fix

#1007 Nerf eternal singularity alternate recipe
  src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
Labels: Affects Balance

#1008 Fix collisions
  src/main/java/com/dreammaster/gthandler/recipes/CircuitAssemblerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptBloodArsenal.java
  src/main/java/com/dreammaster/scripts/ScriptBuildCraft.java
  src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
  src/main/java/com/dreammaster/scripts/ScriptEMT.java
  src/main/java/com/dreammaster/scripts/ScriptEnderIO.java
  src/main/java/com/dreammaster/scripts/ScriptExtraBees.java
  src/main/java/com/dreammaster/scripts/ScriptForestry.java
Labels: bug fix

#1009 Deprecate ic2 semifluid gen
  src/main/java/com/dreammaster/scripts/ScriptEMT.java
  src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
Labels: enhancement

#1010 Buff compressor casings
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: Affects Balance

#1013 Remove loads of duplicate materials
  src/main/java/com/dreammaster/gthandler/CustomItemList.java
  src/main/java/com/dreammaster/gthandler/GT_Loader_Items.java
  src/main/java/com/dreammaster/gthandler/GT_Loader_Materials.java
  src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
  src/main/java/com/dreammaster/item/ItemList.java
  src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
  src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
  src/main/java/com/dreammaster/scripts/ScriptGenetics.java
  src/main/java/com/dreammaster/scripts/ScriptGraviSuite.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
  src/main/resources/assets/dreamcraft/lang/ru_RU.lang
  src/main/resources/assets/dreamcraft/lang/zh_CN.lang
  src/main/resources/assets/dreamcraft/textures/items/itemAluminiumItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemAlumiteDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemArditePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemBedrockiumPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemBlackPlutoniumDensePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemBlackPlutoniumDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemBlackPlutoniumPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemCallistoIceColdIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemCallistoIceDensePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemCallistoIceDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemCallistoIceIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemCallistoIcePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemChromeItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemIridiumItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemLedoxColdIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemLedoxDensePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemLedoxDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemLedoxIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemLedoxPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemManyullynPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemMytrylDensePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemMytrylDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemMytrylHotIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemMytrylIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemMytrylPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemNeutroniumItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemOsmiumItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemQuantinumDensePlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemQuantinumDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemQuantinumHotIngot.png
  src/main/resources/assets/dreamcraft/textures/items/itemQuantinumPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemQuantinumRod.png
  src/main/resources/assets/dreamcraft/textures/items/itemSandDust.png
  src/main/resources/assets/dreamcraft/textures/items/itemStainlessSteelItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemTitaniumItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemTungstenItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemTungstenSteelItemCasing.png
  src/main/resources/assets/dreamcraft/textures/items/itemVoidFoil.png
  src/main/resources/assets/dreamcraft/textures/items/itemVoidPlate.png
  src/main/resources/assets/dreamcraft/textures/items/itemVoidRing.png
  src/main/resources/assets/dreamcraft/textures/items/itemVoidRod.png
Labels: bug fix

#1014 Collisions
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/CentrifugeRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ExtruderRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/FormingPressRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/LatheRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
  src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
Labels: bug fix
