Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-09, with the labels that each got.

#1353 Wire Dupe Fix
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
Labels: bug fix

#1357 Add macerator recycling recipe from Hempcrete back to Hempcrete Powder
  src/main/java/com/dreammaster/gthandler/recipes/MaceratorRecipes.java
Labels: enhancement

#1358 Adds Missing Lootbag Assembler Recipes (& Light Refactor)
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: enhancement

#1359 Add Chisel recipe for EFR Concrete and Concrete Powder
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: enhancement, safe for stable

#1362 Restore overwritten recipes for Warding, Portable Hole, Nine Hells foci
  src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java
Labels: bug fix, safe for stable

#1363 ProjectRed Framed Wire GT Recipes & PR Wire Refactor
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptProjectRed.java
Labels: enhancement, safe for stable, refactor

#1366 Replace Pam's candle with torch in EFR lantern recipe
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: bug fix, safe for stable

#1373 Fixes Diamond Chainsaw in NEI
  src/main/java/com/dreammaster/scripts/ScriptEMT.java
Labels: bug fix

#1378 Removes Duplicate Recipes for Compressed Glowstone
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
Labels: bug fix

#1383 Allow for usage of MetaID range (MetaStart and MetaEnd) to specify the custom tooltip
  src/main/java/com/dreammaster/modctt/CustomToolTips.java
Labels: bug fix, enhancement

#1386 Remove specific slot check and notification for pizza gloves
  src/main/java/com/dreammaster/baubles/OvenGlove.java
Labels: bug fix, safe for stable

#1389 Fix Barnarda C plank recipes
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Labels: bug fix

#1390 Fix Barnarda C plank recipes for 2.8.x branch
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Labels: bug fix
