Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-06, with the labels that each got.

#1286 Hellish blood recipe
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
Labels: :construction: Testing on Zeta

#1261 Replace Mica Insulator with Naquarite
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptTCCoreMod.java
Labels: Affects Balance, new feature, :construction: Testing on Zeta

#1291 Move Custom1-5 Aspect creation to GT5U
  src/main/java/com/dreammaster/main/MainRegistry.java
  src/main/java/com/dreammaster/modfixes/GTpp/GregTechPlusPlusAbandonedAspectsFix.java
  src/main/java/com/dreammaster/modfixes/GTpp/LocalizedAspect.java
  src/main/resources/assets/dreamcraft/textures/thaumcraft/aspect/aequalitas.png
  src/main/resources/assets/dreamcraft/textures/thaumcraft/aspect/astrum.png
  src/main/resources/assets/dreamcraft/textures/thaumcraft/aspect/gloria.png
  src/main/resources/assets/dreamcraft/textures/thaumcraft/aspect/primordium.png
  src/main/resources/assets/dreamcraft/textures/thaumcraft/aspect/vesania.png
Labels: refactor
