Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-05, with the labels that each got.

#1220 Netherite
  src/main/java/com/dreammaster/scripts/ScriptTCCoreMod.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
Labels: enhancement, Affects Balance, :construction: Testing on Zeta

#1254 fix ritual of Unbinding (Blood Magic)
  src/main/java/com/dreammaster/scripts/ScriptBloodMagic.java
Labels: bug fix

#1259 update dtpf infinity circuit to not share circuit with cosmicneut
  src/main/java/com/dreammaster/gthandler/recipes/DTPFRecipes.java
Labels: enhancement

#1247 Add Concrete Clay Bucket & a fuel value for the Creosote Clay Bucket
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/iguana/IguanaProxy.java
  src/main/java/com/dreammaster/main/MainRegistry.java
  src/main/java/com/dreammaster/scripts/ScriptCreosoteBucketFuelValue.java
  src/main/java/com/dreammaster/scripts/ScriptLoader.java
  src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
  src/main/resources/assets/dreamcraft/textures/items/itemClayBucketConcrete.png
Labels: new feature

#1250 Reduce Excessive AL Recipe Times
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
Labels: Affects Balance

#1230 Add adv network switch recipe
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Labels: new feature, :construction: Testing on Zeta

#1249 Remove recipe for gravisuite's vajra, vajra core and magnetron
  dependencies.gradle
  src/main/java/com/dreammaster/scripts/ScriptGraviSuite.java
Labels: :construction: Testing on Zeta

#1271 Fix the armor stand recipe collision
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: bug fix

#1276 Reduce Crafting time of lootbag conversion
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: enhancement

#1267 Update uses of crafting tools
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java
  src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
  src/main/java/com/dreammaster/scripts/ScriptBattleGear.java
  src/main/java/com/dreammaster/scripts/ScriptBiblioCraft.java
  src/main/java/com/dreammaster/scripts/ScriptCarpentersBlocks.java
  src/main/java/com/dreammaster/scripts/ScriptForbiddenMagic.java
  src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
  src/main/java/com/dreammaster/scripts/ScriptHarvestcraft.java
  src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
  src/main/java/com/dreammaster/scripts/ScriptLogisticPipes.java
  src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
  src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
  src/main/java/com/dreammaster/scripts/ScriptStevesCarts.java
  src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
Labels: :construction: Testing on Zeta

#1280 Nerf amount of calcite obtained from geodes
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: Affects Balance

#1228 Yipiii... another batch of recipes
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: :construction: Testing on Zeta
