Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-02, with the labels that each got.

#1192 Move fish trap recipe from gt++ to coremod
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
Labels: :construction: Testing on Zeta

#1193 Add fluid heater recipes for pam's hearvestcraft fresh milk
  src/main/java/com/dreammaster/gthandler/recipes/FluidHeaterRecipes.java
Labels: enhancement, :construction: Testing on Zeta

#1197 Recipe adjustment for the bulk catalyst housing
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Labels: enhancement

#1196 Fix some references to GT++ items
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/CompressorRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptCompactKineticGenerators.java
  src/main/java/com/dreammaster/scripts/ScriptExtraUtilities.java
  src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
  src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
  src/main/java/com/dreammaster/scripts/ScriptThaumicBases.java
Labels: bug fix, :construction: Testing on Zeta

#1198 Buff neutronium and Cosmic Neutronium smelting times
  src/main/java/com/dreammaster/gthandler/recipes/BlastFurnaceRecipes.java
Labels: Affects Balance, :construction: Testing on Zeta

#1206 Reduce Obsidian Processing from 9 per block to 2 per block
  src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
Labels: bug fix, Affects Balance

#1204 Coremod updates for Refactoring GT++ 2025-02-17
  src/main/java/com/dreammaster/gthandler/recipes/VacuumFurnaceRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptGregtechPlusPlus.java
Labels: :construction: Testing on Zeta

#1185 New batch of EFR recipes
  dependencies.gradle
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
Labels: :construction: Testing on Zeta

#1201 Qol recipes
  src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
  src/main/java/com/dreammaster/scripts/ScriptChisel.java
  src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
  src/main/java/com/dreammaster/scripts/ScriptNatura.java
  src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
  src/main/java/com/dreammaster/scripts/ScriptTwilightForest.java
Labels: Affects Balance, :construction: Testing on Zeta

#1207 RC Firestone for LV Age
  src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
Labels: Affects Balance, :construction: Testing on Zeta

#1211 fix wrong recipes in circuit assemblers for preconfigured storage buses
  src/main/java/com/dreammaster/scripts/ScriptAE2FC.java
  src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
Labels: safe for stable

#1210 Adapt to pipe rename
  gradle.properties
  src/main/java/com/dreammaster/gthandler/GT_Loader_ItemPipes.java
Labels: :construction: Testing on Zeta

#1208 Coremod updates for Refactoring GT++ 2025-02-19
  src/main/java/com/dreammaster/scripts/ScriptBiomesOPlenty.java
Labels: :construction: Testing on Zeta
