Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-08, with the labels that each got.

#1310 Convert Travellers Gear armor stands to a chest
  src/main/java/com/dreammaster/main/MainRegistry.java
  src/main/java/com/dreammaster/travellersgear/TGConverter.java
Labels: bug fix

#1325 Add deepslate dust
  src/main/java/com/dreammaster/item/NHItemList.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
  src/main/resources/assets/dreamcraft/textures/items/itemDeepslateDust.png
Labels: enhancement

#1330 Fix: Remove direct Macerator Recipe which causes issue with nei-custom-diagrams
  src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
Labels: bug fix

#1319 Add Tipped Arrow & Cherry Plank Recipes for EFR
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
  src/main/java/com/dreammaster/scripts/ScriptIronTankMinecarts.java
Labels: bug fix, enhancement, :construction: Testing on Zeta

#1337 bring tantalum freeze time to a reasonable level
  src/main/java/com/dreammaster/gthandler/recipes/VacuumFreezerRecipes.java
Labels: Affects Balance

#1343 Adds Recipe for Super Stock Replenisher & Makes Void Cell Recipe Consistent
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
Labels: enhancement

#1345 Adds controller recipe for steam alloy smelter
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: enhancement, safe for stable

#1346 Qol singularity
  src/main/java/com/dreammaster/scripts/ScriptAppliedEnergistics2.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: new feature

#1348 Adds Alternate Rubber Recipes for EIO Conduit Binder
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalBathRecipes.java
Labels: enhancement

#1331 made deepslate viable
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/ElectrolyzerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: enhancement, Affects Balance

#1350 netherite dupe fix
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: bug fix
