Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-01, with the labels that each got.

#1142 Fix artificial universe cell
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Labels: bug fix, :construction: Testing on Zeta

#1140 GS script recipes fixes
  src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Labels: bug fix, :construction: Testing on Zeta

#1129 Change Bio Vat Recipes to use new metadata
  src/main/java/com/dreammaster/bartworksHandler/BW_RadHatchMaterial.java
  src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java
  src/main/java/com/dreammaster/bartworksHandler/BioItemLoader.java
Labels: :construction: Testing on Zeta

#1141 Rebalance scanning times
  src/main/java/com/dreammaster/bartworksHandler/BW_Recipe_Loader.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
  src/main/java/com/dreammaster/scripts/ScriptGalaxySpace.java
Labels: Affects Balance

#1152 Add NC hatch recipes
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
Labels: enhancement

#1144 Retier CRIB, proxy, adv stocking hatch
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/SpaceAssemblerRecipes.java
Labels: :construction: Testing on Zeta

#1161 Convert solar panel recipes
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/AssemblingLineRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptAdvancedSolarPanel.java
  src/main/java/com/dreammaster/scripts/ScriptSuperSolarPanels.java
Labels: enhancement

#1166 Remove iridium plate recipe from double ingot
  src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
Labels: :construction: Testing on Zeta

#1168 Remove map recipe from crafting and recipe removal logic
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
Labels: bug fix

#1176 Fix duplicate solar conversion
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
Labels: bug fix

#1181 Replace Aluminum Gravel Ore with Zinc Gravel Ore, and deal with the consequences
  src/main/java/com/dreammaster/gthandler/GT_Loader_Materials.java
  src/main/java/com/dreammaster/gthandler/recipes/AlloySmelterRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/FluidExtractorRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/MixerRecipes.java
  src/main/java/com/dreammaster/gthandler/recipes/NeutroniumCompressorRecipes.java
  src/main/java/com/dreammaster/main/MainRegistry.java
  src/main/java/com/dreammaster/main/NHItems.java
  src/main/java/com/dreammaster/scripts/ScriptAvaritia.java
  src/main/java/com/dreammaster/scripts/ScriptCoreMod.java
  src/main/java/com/dreammaster/scripts/ScriptMechworks.java
  src/main/java/com/dreammaster/scripts/ScriptTinkersConstruct.java
  src/main/java/com/dreammaster/tinkersConstruct/SmelteryFluidTypes.java
  src/main/java/com/dreammaster/tinkersConstruct/TConstructHelper.java
  src/main/java/com/dreammaster/tinkersConstruct/TiCoLoader.java
  src/main/java/com/dreammaster/tinkersConstruct/worldgen/ZincGravelOre.java
  src/main/java/com/dreammaster/tinkersConstruct/worldgen/ZincGravelOreItem.java
  src/main/java/com/dreammaster/tinkersConstruct/worldgen/ZincGravelWorldgen.java
  src/main/resources/META-INF/dreamcraft_at.cfg
  src/main/resources/assets/dreamcraft/lang/en_US.lang
  src/main/resources/assets/dreamcraft/textures/blocks/ore_zinc_gravel.png
  src/main/resources/assets/dreamcraft/tinker/manuals/smeltery.xml
Labels: Affects Balance, :construction: Testing on Zeta
