Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-07, with the labels that each got.

#1296 Remove access to GTMod isclient methods
  src/main/java/com/dreammaster/main/ClientProxy.java
  src/main/java/com/dreammaster/main/CommonProxy.java
  src/main/java/com/dreammaster/main/MainRegistry.java
  src/main/java/com/dreammaster/scripts/ScriptZZClientOnly.java
Labels: refactor

#1304 Remove tunstensteel from MM MK0
  src/main/java/com/dreammaster/scripts/ScriptMatterManipulator.java
Labels: bug fix, Affects Balance

#1303 Removes Plantball -) Sugarcane Forge Hammer Recipe
  src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
Labels: bug fix

#1306 Fixes Decompression Recipes for Coal & Charcoal
  src/main/java/com/dreammaster/gthandler/recipes/ForgeHammerRecipes.java
Labels: bug fix

#1308 Update MOTD Banner
  src/main/java/com/dreammaster/client/util/GTNHPauseScreen.java
  src/main/java/com/dreammaster/lib/Refstrings.java
  src/main/java/com/dreammaster/loginhandler/LoginHandler.java
  src/main/resources/assets/dreamcraft/lang/en_US.lang
Labels: enhancement

#1302 EFR - Change / Add Sign Crafting & Assembler Recipes
  src/main/java/com/dreammaster/scripts/ScriptMinecraft.java
Labels: enhancement

#1314 Fixes Recipe Conflict Between Armor Stand and Chisel
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: bug fix

#1313 Adds recipes for EFR boats & boats with chests
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: enhancement

#1285 Update IC2 Script
  dependencies.gradle
  src/main/java/com/dreammaster/gthandler/recipes/ChemicalReactorRecipes.java
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptEMT.java
  src/main/java/com/dreammaster/scripts/ScriptGregtech.java
  src/main/java/com/dreammaster/scripts/ScriptIndustrialCraft.java
  src/main/java/com/dreammaster/scripts/ScriptThaumcraft.java
Labels: :construction: Testing on Zeta, refactor
