Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-03, with the labels that each got.

#1213 New batch ( and I think last one of simple recipes)
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: :construction: Testing on Zeta

#1223 Add iron barrel + upgrade recipes
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: :construction: Testing on Zeta

#1225 Fix iron and copper barrel upgrades
  src/main/java/com/dreammaster/scripts/ScriptEFR.java
Labels: bug fix

#1212 Create new crafting recipes for upgrading transposers with Fluid Regulators
  src/main/java/com/dreammaster/gthandler/recipes/AssemblerRecipes.java
  src/main/java/com/dreammaster/scripts/ScriptOpenComputers.java
Labels: Affects Balance

#1226 Hotfix: Reflect change to GT Hazard API
  dependencies.gradle
  src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java
Labels: bug fix
