Repository GTNewHorizons/NewHorizonsCoreMod, pull requests merged in 2025-04, with the labels that each got.

#1234 Add Iron Tank Minecarts and unify Tank Cart recipes
  dependencies.gradle
  src/main/java/com/dreammaster/recipes/RecipeRemover.java
  src/main/java/com/dreammaster/scripts/ScriptIronTankMinecarts.java
  src/main/java/com/dreammaster/scripts/ScriptLoader.java
  src/main/java/com/dreammaster/scripts/ScriptRailcraft.java
Labels: Affects Balance

#1241 Improve forbidden isModLoaded and getModItem scripts
  .github/workflows/test-forbidden-getmoditems.yml
  .github/workflows/test-forbidden-ismodloaded.yml
  src/main/java/com/dreammaster/main/MainRegistry.java
  src/main/java/com/dreammaster/modcustomdrops/CustomDropsHandler.java
  src/main/java/com/dreammaster/scripts/ScriptAmunRa.java
  src/main/java/com/dreammaster/scripts/ScriptGalacticraft.java
  src/main/java/com/dreammaster/scripts/ScriptThaumicEnergistics.java
  src/main/java/com/dreammaster/scripts/ScriptZZClientOnly.java
Labels: :construction: Testing on Zeta

#1246 Revert Oredict call on Electron-Permeable glass recipe
  src/main/java/com/dreammaster/gthandler/recipes/FluidSolidifierRecipes.java
Labels: bug fix, :construction: Testing on Zeta
